---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: env
  namespace: findingway
spec:
  encryptedData:
    DISCORD_TOKEN: AgAsN+ed1rjiB1a/3z2e8EIf21XOTzB0HrScdNB8ShLrdD2nk4isFPxuYuSwm71NOgJPumZVdwQbbNe+ydtns5/srJcMOxdqb5iOmxl4JaYCuSLYHn67Uz9wKm7RjQiddssyw0z+i1XQJ+r6xhw6CfU5v+XvPF+rIoBQbykiU1myuno7F3tYANyyd/HQzQOH/tzlnk/I+HNTR9NmHJ2Z8nbIm2EQmEAY4zOOFq2U+HeMgazqJYh1JyJ3/wr1ckXsc7MbcZzuZEPhoQBNW8sv1tcVdaJ44mjAUVNJigIIj1Vu1RwKzTnUumevt29fUITJUwRqr5ynSd8SkIROcxN8CePQj7pUHKmbVFN5b/gpN0dSZ3yoreZaZ0anMrTQM6yLeuQ0Cd714Oi20Cd8JMuhF8SNUqKuljRgHp2RK9M/IpbbVzi/aTCdWzAaXXsh8QqV/J0uhrWhPnSh1EAEE/HCxBM7k/W+Ok1MelyMPpwIxepFmteKpZncN9/gvZRJ2jxX+ee+t9KM03haXaSNWHeEtI098Jd5PhnA5KQRJ1r8V1Kisu0GeZZjDOzNhH+JafYbL7nUlwk1DQWX3iTpY6suHJo0/nnqGmduFdqL7Qo/mFeyvRc/QNS4xOGsxI4/GC/sREmfk2QH1ZxrHd/ftNKhrZ9Ls1UWIyKR19O8DCqYAJrxo+mLq3efyNRRFrpF4jyYo+vPtM7siFBHD+DMnuuhuFv6rTgSIQbadCSB2QzE7qnr11lFvCHl6VK1FY7Y04CzNFw1aMX6YxmxmsbPLDVx5dOK9yrgDCi+Pg==
  template:
    metadata:
      creationTimestamp: null
      name: env
      namespace: findingway
